### ISSUE TITLE
local game error when finished

### ISSUE THREAD

**Issue by Pommfritz0308** [memaar92/transcendence#104]
after end of local game -> redirection to tournament_preview occurs

[local_game_error.log](https://github.com/user-attachments/files/17524356/local_game_error.log)
![Screenshot from 2024-10-25 17-37-10](https://github.com/user-attachments/assets/7a16a9cf-cc80-4563-a474-f36b3298239e)

additionally the local storage shows a tournament called "notify" that I did not create...

![Screenshot from 2024-10-25 17-46-13](https://github.com/user-attachments/assets/818d4416-4811-4799-a27c-24bffa5f6098)

**Comment by wrottger** [comment]
this should be fixed with [923b134](https://github.com/memaar92/transcendence/pull/101/commits/923b1342b1292639b0bd8dc8e3c43b65d7192e24).

> additionally the local storage shows a tournament called "notify" that I did not create...

This is impossible. The tournament name used to stay in memory for as long as you didn't create a new one.
