### ISSUE TITLE
logout button (+ account delete + user info edit buttons) are not triggering

### ISSUE THREAD

**Issue by memaar92** [memaar92/transcendence#81]

**Comment by wrottger** [comment]
Das war schon auf Freddys branch so. Muss mit seinen changes zusammenhängen. Ich werde es mir mal anschauen.

**Comment by memaar92** [comment]
der Test fand in Freddys branch statt. Aufgrund der issues ja auch noch nicht gemerged

**Comment by wrottger** [comment]
@memaar92 Habe ich zu spät gesehen
