### ISSUE TITLE
router doesn't refresh the expired access token when the page is manually refreshed --> user is logged out

### ISSUE THREAD

**Issue by Pommfritz0308** [memaar92/transcendence#89]

**Comment by wrottger** [comment]
Has to do with /token/check not returning json["code"] = "token_not_valid"

**Comment by wrottger** [comment]
that fixed it

**Comment by memaar92** [comment]
/token/check is not supposed to be returning json["code"] = "token_not_valid" (some time ago, we defined together that it should always return 200 and the info if user is logged in or not)

**Comment by memaar92** [comment]
@wrottger please check if your changes are not breaking something else in the app, because back then you explicitly asked for the 200 return code with logged-in or not json.

**Comment by memaar92** [comment]
@wrottger It is definitely breaking other stuff. E.g. when just navigate to localhost now (after a fresh build), you are getting a toast stating "Error: please log in". Also, it will break a check in the chatHandler.js
Please test at least a bit before pushing

**Comment by memaar92** [comment]
thumbs down means you can replicate it or means you are not gonna test? (or something else?)

**Comment by memaar92** [comment]
reverted changes for now to unblock chat PR
