### ISSUE TITLE
winning_screen

### ISSUE THREAD

**Issue by StrongCoding** [memaar92/transcendence#90]
i create two users:
user_id: 1
user_id: 2

user 1 added user 2 to friend list
user 2 accepted

user 1 invites user 2 via chat to an online game

user 1 is on the right side
user 2 is on the left side

user 1 wins -> get you loose screen
user 2 lost -> gets you win screen

in both stats its saying user 2 wins and user 1 lost

**Comment by memaar92** [comment]
Haben Freddy und ich eigentlich gerade genau so getestet und bei uns hat es sich wir erwartet verhalten

**Comment by memaar92** [comment]
Konnte ich jetzt genau so replizieren. Bekomme auch vertauschte Meldungen und vertauschte game history

**Comment by memaar92** [comment]
Wer wem die Freudschaftsanfrage schickt, scheint uebrigens egal zu sein. Aber ja, es scheint relevant zu sein, dass user 1 (mit niedrigerer user id) derjenige ist, der einlaedt.

Ich assigne mal Steve und Wayne
